@hostname = http://localhost:8000

get {{hostname}}

###

get {{hostname}}/list-files

###

get {{hostname}}/processing-status

###

GET {{hostname}}/debug-paths

###

DELETE {{hostname}}/processing-status

###

DELETE {{hostname}}/processing-status/{filename}