### Upload file to OpenAI
# @name uploadFile
POST https://api.openai.com/v1/files
Authorization: Bearer {{$dotenv OPENAI_API_KEY}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="purpose"

assistants
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="shortnames.py"
Content-Type: text/plain

./shortnames.py
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### List files
# @name listFiles
GET https://api.openai.com/v1/files
Authorization: Bearer {{$dotenv OPENAI_API_KEY}}

### Retrieve file
# @name retrieveFile
GET https://api.openai.com/v1/files/{fileId}
Authorization: Bearer {{$dotenv OPENAI_API_KEY}}

### Delete file
# @name deleteFile
DELETE https://api.openai.com/v1/files/file-GPddo2kxzPavQYfN4bqToE
Authorization: Bearer {{$dotenv OPENAI_API_KEY}}

### Attach file to asst.
POST https://api.openai.com/v1/assistants/{{$dotenv OPENAI_ASSISTANT_ID}}/files
Authorization: Bearer {{$dotenv OPENAI_API_KEY}}
OpenAI-Beta: assistants=v2
Content-Type: application/json

{
    "file_id": "file-GPddo2kxzPavQYfN4bqToE"
}