@hostname = pdf-proc.onrender.com

GET {{hostname}}

###

POST -F "file=@/full/path/to/your/file.pdf" https://pdf-process.fly.dev/upload/

###

POST {{hostname}}/uploads/


###

POST {{hostname}}/process/041025.zip

###
get {{hostname}}/list-files

###

get {{hostname}}/processing-status/

###

get {{hostname}}/processing-status/80114.pdf

###

GET {{hostname}}/debug-paths

###

DELETE {{hostname}}/processing-status

###

DELETE {{hostname}}/processing-status/510905_20250401_30567843_14160915113.pdf

###
GET {{hostname}}